export const READ_ONLY_FLOW_PROPS = {
  nodesDraggable: false,
  nodesConnectable: false,
  nodesFocusable: false,
  edgesFocusable: false,
  edgesReconnectable: false,
  elementsSelectable: false,
  selectNodesOnDrag: false,
  panOnDrag: false,
  panOnScroll: false,
  zoomOnScroll: false,
  zoomOnPinch: false,
  zoomOnDoubleClick: false,
  connectOnClick: false,
  autoPanOnNodeDrag: false,
  autoPanOnConnect: false,
  autoPanOnNodeFocus: false,
  autoPanOnSelection: false,
  deleteKeyCode: null,
  selectionKeyCode: null,
  multiSelectionKeyCode: null,
  panActivationKeyCode: null,
  zoomActivationKeyCode: null,
  preventScrolling: false,
  disableKeyboardA11y: true,
} as const;
