export type LexiconEntry = {
  term: string;
  weight: number;
  category: string;
  aliases?: string[];
};

const ACTION_ENTRIES: LexiconEntry[] = [
  entry('创建', 1, 'action', ['新建', '添加', '增加', '加上']),
  entry('删除', 1, 'action', ['移除', '去掉']),
  entry('修改', 1, 'action', ['调整', '更改']),
  entry('连接', 1, 'action', ['连到', '接到']),
  entry('插入', 1, 'action', ['加在后面']),
  entry('生成', 1, 'action', ['绘制', '画一个', '画一张']),
  entry('保存', 1, 'action', ['存储']),
  entry('恢复', 1, 'action', ['还原']),
  entry('导出', 1, 'action', ['输出']),
  entry('确认', 1, 'control', ['应用', '采用']),
  entry('取消', 1, 'control', ['算了']),
  entry('暂停', 1, 'control', ['停一下']),
  entry('继续', 1, 'control', ['接着执行']),
  entry('撤销', 1, 'control', ['撤消', '回到上一步']),
  entry('重做', 1, 'control', ['再做一次']),
  entry('放大', 1, 'viewport'),
  entry('缩小', 1, 'viewport'),
  entry('看全图', 1, 'viewport', ['显示完整画布', '适应屏幕']),
  entry('聚焦', 0.95, 'viewport', ['查看节点']),
];

const DIAGRAM_ENTRIES: LexiconEntry[] = [
  entry('流程图', 1, 'diagram'),
  entry('系统架构图', 1, 'diagram', ['架构图', '服务架构', '技术架构']),
  entry('节点', 1, 'diagram'),
  entry('连线', 1, 'diagram'),
  entry('分支', 1, 'diagram'),
  entry('主流程', 1, 'diagram'),
  entry('异常分支', 1, 'diagram'),
  entry('开始节点', 0.95, 'node_type', ['开始', '起点']),
  entry('结束节点', 0.95, 'node_type', ['结束', '终点']),
  entry('流程节点', 0.95, 'node_type', ['流程']),
  entry('判断节点', 0.95, 'node_type', ['判断', '条件']),
  entry('数据库节点', 0.95, 'node_type', ['数据库']),
  entry('服务节点', 0.95, 'node_type', ['服务']),
  entry('用户节点', 0.95, 'node_type', ['用户']),
  entry('外部系统节点', 0.95, 'node_type', ['外部系统']),
  entry('标签', 0.9, 'diagram'),
  entry('名称', 0.9, 'diagram'),
  entry('样式', 0.9, 'diagram'),
  entry('颜色', 0.9, 'diagram'),
  entry('实线', 0.95, 'edge_style'),
  entry('虚线', 0.95, 'edge_style'),
  entry('高亮', 0.95, 'edge_style'),
  entry('弱化', 0.95, 'edge_style'),
  entry('红色', 0.95, 'color'),
  entry('蓝色', 0.95, 'color'),
  entry('绿色', 0.95, 'color'),
  entry('黄色', 0.95, 'color'),
  entry('灰色', 0.95, 'color'),
];

const WORKFLOW_ENTRIES: LexiconEntry[] = [
  entry('横向布局', 1, 'layout', ['从左到右']),
  entry('纵向布局', 1, 'layout', ['从上到下']),
  entry('自动排版', 1, 'layout', ['重新排版', '整理布局']),
  entry('版本', 0.95, 'workflow'),
  entry('保存当前版本', 1, 'workflow'),
  entry('列出版本', 1, 'workflow', ['查看版本', '有哪些版本']),
  entry('恢复版本', 1, 'workflow', ['回到版本']),
  entry('对比版本', 1, 'workflow'),
  entry('自动美化', 1, 'workflow'),
  entry('汇报版', 0.95, 'workflow'),
  entry('蓝色商务风', 0.95, 'workflow'),
  entry('汇报简洁风', 0.95, 'workflow'),
  entry('技术深色风', 0.95, 'workflow'),
  entry('突出主流程', 1, 'workflow'),
  entry('弱化异常分支', 1, 'workflow'),
  entry('隐藏异常分支', 1, 'workflow'),
  entry('显示异常分支', 1, 'workflow'),
  entry('登录流程', 0.9, 'scene'),
  entry('电商订单流程', 0.9, 'scene'),
  entry('系统架构', 0.9, 'scene'),
  entry('导出 JSON', 1, 'export'),
  entry('导出 SVG', 1, 'export'),
  entry('导出 PNG', 1, 'export'),
  entry('导出图片', 1, 'export'),
];

const BUSINESS_ENTRIES: LexiconEntry[] = [
  entry('登录', 0.85, 'business'),
  entry('注册', 0.85, 'business'),
  entry('验证码', 0.85, 'business'),
  entry('身份认证', 0.85, 'business'),
  entry('权限校验', 0.85, 'business'),
  entry('人工审核', 0.85, 'business'),
  entry('审批', 0.85, 'business'),
  entry('提交申请', 0.85, 'business'),
  entry('订单', 0.85, 'business'),
  entry('支付', 0.85, 'business'),
  entry('退款', 0.85, 'business'),
  entry('库存', 0.85, 'business'),
  entry('物流', 0.85, 'business'),
  entry('消息队列', 0.85, 'architecture'),
  entry('API 网关', 0.85, 'architecture'),
  entry('负载均衡', 0.85, 'architecture'),
  entry('缓存', 0.85, 'architecture'),
  entry('数据库', 0.85, 'architecture'),
  entry('微服务', 0.85, 'architecture'),
  entry('用户端', 0.85, 'architecture'),
  entry('服务端', 0.85, 'architecture'),
  entry('成功', 0.9, 'branch'),
  entry('失败', 0.9, 'branch'),
  entry('正常', 0.9, 'branch'),
  entry('异常', 0.9, 'branch'),
  entry('通过', 0.9, 'branch'),
  entry('拒绝', 0.9, 'branch'),
  entry('超时', 0.9, 'branch'),
];

export const BUILTIN_ASR_LEXICON: LexiconEntry[] = [
  ...ACTION_ENTRIES,
  ...DIAGRAM_ENTRIES,
  ...WORKFLOW_ENTRIES,
  ...BUSINESS_ENTRIES,
];

export const ASR_ERROR_MAPPINGS: Array<[RegExp, string]> = [
  [/流成图|流程途|流程兔/g, '流程图'],
  [/架够图|价构图|架构途/g, '架构图'],
  [/声成|生成成/g, '生成'],
  [/话一个|化一个/g, '画一个'],
  [/强化学西|强化学习习/g, '强化学习'],
  [/节典/g, '节点'],
  [/连现|连县/g, '连线'],
  [/登路|登陆/g, '登录'],
  [/布橘|部局/g, '布局'],
  [/排板/g, '排版'],
  [/撤消/g, '撤销'],
  [/到出/g, '导出'],
  [/横像/g, '横向'],
  [/纵像/g, '纵向'],
  [/看泉图/g, '看全图'],
  [/宝存/g, '保存'],
  [/取笑/g, '取消'],
  [/却认/g, '确认'],
];

export const PINYIN_CONFUSION_GROUPS = [
  '向像象',
  '布部不',
  '局橘菊',
  '流留刘',
  '程成城',
  '图途兔',
  '架价假',
  '构够购',
  '节结杰',
  '点典店',
  '连联莲',
  '线现县限',
  '登灯',
  '录路陆',
  '版板班',
  '撤彻',
  '销消萧',
  '确却',
  '认任',
  '取娶',
  '全泉权',
  '导到倒',
  '出初',
  '存村',
  '强墙',
  '化话画',
  '学雪',
  '习西',
  '排牌',
  '保宝',
  '存寸',
  '分份',
  '支只',
  '服福',
  '务物',
  '数树',
  '据句',
  '库裤',
  '用永',
  '户护',
  '审省',
  '核盒',
  '验眼',
  '证正',
  '成层',
  '功工',
  '失师',
  '败拜',
  '异意',
  '常长',
  '显险',
  '示是',
  '主住',
  '题提',
  '名明',
  '称撑',
  '改该',
  '删山',
  '除厨',
  '增曾',
  '加家',
  '接结',
  '入如',
  '恢灰',
  '复付',
  '导岛',
  '缩索',
  '小晓',
  '放访',
  '大达',
  '核合盒',
];

export function getBuiltInLexiconStats() {
  return {
    canonicalTerms: BUILTIN_ASR_LEXICON.length,
    aliases: BUILTIN_ASR_LEXICON.reduce(
      (count, item) => count + (item.aliases?.length ?? 0),
      0,
    ),
    errorMappings: ASR_ERROR_MAPPINGS.length,
    phoneticGroups: PINYIN_CONFUSION_GROUPS.length,
  };
}

function entry(
  term: string,
  weight: number,
  category: string,
  aliases?: string[],
): LexiconEntry {
  return { term, weight, category, aliases };
}
